### ISSUE TITLE
Export spritesheet duplicates linked frames

### ISSUE THREAD

**Issue by devnewton** [LibreSprite/LibreSprite#82] opened 2020-10-26 15:14 UTC
When you export a sprite (like following example), LibreSprite duplicates linked frames.

Code comment mention linked frame reuse attempt:

https://github.com/LibreSprite/LibreSprite/blob/8eedb673ce340c5fbb26aaa0cacff491377cc917/src/app/document_exporter.cpp#L480

[vautour.zip](https://github.com/LibreSprite/LibreSprite/files/5439603/vautour.zip)

**Comment by jjhaggar** [comment] 2021-08-06 08:37
Hi, @devnewton !

Could you add a pair of screenshots to explain the problem? I'm not sure (I don't know c++), but I think the export function works as intended, because you cannot link frames, but cells (for example, if you have more layers and some of those cells aren't linked it would make no sense to skip them in the export).

Example:
![image](https://user-images.githubusercontent.com/4078392/128482152-aeaf030d-a62a-4003-bfc4-292a00ba535a.png)

Result:
![image](https://user-images.githubusercontent.com/4078392/128482185-8174f03c-80d5-40a5-a670-c8481fd18d6d.png)

Please have a look at the screenshots and confirm if that's what you meant, so we can close this issue :)

**Comment by devnewton** [comment] 2021-08-09 12:34
Here is a sample:

![image](https://user-images.githubusercontent.com/1859457/128706343-7b601eda-dc77-4115-b681-2cd777b31d38.png)

![image](https://user-images.githubusercontent.com/1859457/128706389-36ce67f4-1c18-4550-84db-fb655ce9bdf5.png)

[tengu2.zip](https://github.com/LibreSprite/LibreSprite/files/6954520/tengu2.zip)

**Comment by maujin111** [comment] 2021-08-11 08:38
I will check that

**Comment by jjhaggar** [comment] 2021-09-02 18:14
As I thought, this is not a bug, this is just the normal, expected behaviour. 

Maybe we could add an option in "the save as" menu (and also in "save as copy", "export spritesheet", etc.), letting the user choose if they want to merge linked frames when possible (for example, if there is only one layer). Something like this:
![image](https://user-images.githubusercontent.com/4078392/131895304-47e59947-069f-48eb-ab14-5a080e3d9b72.png)

**Closed** 2021-09-13 19:49 UTC
