### ISSUE TITLE
Setup Travis CI for build AppImage

### ISSUE THREAD

**Issue by Symbian9** [LibreSprite/LibreSprite#19] opened 2018-05-04 21:58 UTC
- https://github.com/AppImage/AppImageKit
- https://en.wikipedia.org/wiki/AppImage

Cast @probonopd

### RELATED

- https://github.com/LibreSprite/LibreSprite/issues/17

**Comment by probonopd** [comment] 2018-05-04 21:59
Duplicate of https://github.com/aseprite/aseprite/issues/1044

Reminds me of https://twitter.com/probonopd/status/779769917931487232 - what came out of it?

**Comment by Symbian9** [comment] 2018-05-04 22:04
> ~~Duplicate~~

This is not duplicate, as ~~aseprite-gpl~~ *LibreSprite* now is independent project ;-)

- https://github.com/aseprite-gpl/aseprite/issues/8
- https://github.com/aseprite-gpl/aseprite/issues/10

**Comment by probonopd** [comment] 2018-05-04 22:05
Ah, thanks, wasn't aware.

**Comment by Symbian9** [comment] 2018-06-19 04:39
So, now project in [active rebranding](https://github.com/LibreSprite/LibreSprite/issues/10#issuecomment-394151936) to `LibreSprite` ! ;-)

- https://github.com/LibreSprite/LibreSprite/

Can you now create pull request for setup `continues` builds as AppImage?

**Comment by probonopd** [comment] 2018-06-19 05:48
Can we do without this?
https://github.com/LibreSprite/LibreSprite/commit/70b759a95b3ce5e7c4e99cc00824576961ee2572

Needing a newer libstdc++ than what comes with the oldest still-supported distribution (currently Ubuntu 14.04 LTS) causes additional complexity; see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems.

One would have to use a workaround like https://github.com/darealshinji/AppImageKit-checkrt/issues/1#issuecomment-370134384

**Comment by akien-mga** [comment] 2018-06-19 06:46
> So, now project in active rebranding to LibreSprite ! ;-)

The comment you linked clearly mentions that it's not an *active* rebranding. ;) See also https://github.com/LibreSprite/LibreSprite/issues/1#issuecomment-394152050

That said, if someone wants to set up CI to generate AppImages of the latest master commits, that's fine with me.

**Comment by akien-mga** [comment] 2018-06-19 06:51
> Can we do without this? 70b759a

AFAIK GCC 4.8 is already the version shipped on Ubuntu 14.04 LTS, so this commit at most ensures that it's the latest bugfix release. The GCC version itself is not so much of an issue as long as you build against an old enough glibc. libgcc_s and libstdc++ can be linked statically if need be to increase portability. So as long as it's building on Ubuntu 14.04, what compiler version is used doesn't matter so much, as long as this compiler was linked against Ubuntu 14.04's glibc (I build Godot binaries against GCC 8 on Ubuntu 14.04 and they work great on all distros).

**Comment by Symbian9** [comment] 2018-06-19 08:11
> That said, if someone wants to set up CI to generate AppImages of the latest master commits, that's fine with me.

@akien-mga, we with @probonopd understand that we should create pull request firstly ;-) Open-source development is 'co-working' process.

P.S.: I mostly use *GrafX2*, but interested in supporting/promoting *LibreSprite* development as possible, as I can:

- https://news.ycombinator.com/item?id=17343864

**Comment by probonopd** [comment] 2018-06-19 16:55
> libgcc_s and libstdc++ can be linked statically if need be to increase portability

How would one do that? (That's great - it may save us from workarounds like [this](https://github.com/darealshinji/AppImageKit-checkrt/issues/1#issuecomment-370134384))

**Comment by akien-mga** [comment] 2018-06-19 18:30
>> libgcc_s and libstdc++ can be linked statically if need be to increase portability
> How would one do that? (That's great - it may save us from workarounds like this)

Passing `-static-libgcc -static-libstdc++` to the linker does the trick for GCC. I don't know if it would work with Clang or if it has similar options.
Example: https://github.com/godotengine/godot/blob/master/platform/x11/detect.py#L290-L292

**Comment by probonopd** [comment] 2018-06-20 05:32
Thanks @akien-mga, this could be useful in a lot of cases for this and other applications. Does this work specifically for LibreSprite only or would this work for any libstdc++ based application? Do the build scripts need to be set up specifically to allow for this this?

**Comment by Symbian9** [comment] 2019-01-15 01:20
Any news? Seems like 40 commits coming since LibreSprite forked from Aseprite, so it's a time to setup 'nightly' builds! ;-)

### Setup AppImage build for LibreSprite

Compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:

- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

### TODO

1. https://github.com/appimage/appimagekit
1.1 https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/probonopd/uploadtool

**PLEASE NOTE:** For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) **prior to merging this**, if you haven't already done so. Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

If you have questions, AppImage developers (i.e. @probonopd and other) are on #AppImage on irc.freenode.net.

**Comment by probonopd** [comment] 2019-01-15 06:40
Let me know if you need help.

**Comment by MatteoJoliveau** [comment] 2019-07-03 11:53
Can I suggest [CircleCI](https://circleci.com) instead of Travis?
It has a free plan for open source projects and since its pipelines are based on Docker containers regular shell commands we could set up the environment with all the correct compiler and library versions.

**Comment by probonopd** [comment] 2019-07-03 17:31
Of course you can use any CI service you like. But if you need help from me, I can only help with Travis CI and GitLab CI because I have never used any others.

**Closed** 2020-07-02 10:04 UTC
Labels: enhancement
