### ISSUE TITLE
Not secure program message on installer

### ISSUE THREAD

**Issue by maujin111** [LibreSprite/LibreSprite#64] opened 2020-07-06 23:33 UTC
When i download de installers show me a messenge telling me that the file was not secure and should not be dowload, also when and tried to install it on windows the S.O. show me another messege telling me that install that program could be dangerous. I think that kind of messenges hurts the people trust and take us credibility. P.S the anti-virus was desable all the time

**Comment by MintStudios** [comment] 2020-07-07 01:04
I think the app has to be signed. That just happens when you download a exe. You could put it in a zip file so that doesn't happen.

**Comment by PerryHugh** [comment] 2020-07-07 01:08
We would have to apply to have Microsoft provide a vender code signing certificate. Not sure if it costs any money, but [this](https://docs.microsoft.com/en-us/windows/win32/win_cert/windows-certification-portal) might help.

**Comment by maujin111** [comment] 2020-07-07 01:44
I did a little research and found [these](https://stackoverflow.com/questions/252226/signing-a-windows-exe-file) options, some seem viable and interesting.

**Comment by Zughy** [comment] 2021-09-17 11:28
Duplicate of #80, closing in favour of that

**Closed by Zughy** 2021-09-17 11:28 UTC
Labels: OS: Mac, OS: Windows
