### ISSUE TITLE
Wiki returns error 403

### ISSUE THREAD

**Issue by maska228** [LibreSprite/LibreSprite#118] opened 2021-05-29 11:37 UTC
![image](https://user-images.githubusercontent.com/67519438/120068820-e8f1ca00-c0ac-11eb-9b79-7ce64e06f004.png)

![image](https://user-images.githubusercontent.com/67519438/120068812-d8d9ea80-c0ac-11eb-8f26-1e51ef514403.png)

**Comment by maujin111** [comment] 2021-05-29 11:53
Duplicate of #111 Currently working on it

**Comment by Zughy** [comment] 2021-08-02 21:32
(close it?)

**Closed** 2021-08-03 12:45 UTC
