### ISSUE TITLE
Crash When Loading Fonts on Insert Text

### ISSUE THREAD

**Issue by WallucePinkham** [LibreSprite/LibreSprite#384] opened 2022-12-27 22:51 UTC
##### LibreSprite version

```
1.2-973d0e3d-sdl
```

##### Describe the bug
When I load certain fonts (like fibberfish) the app crashes.

##### To Reproduce
Add Text, click on Font (e.g. Fibberfish). The app crashes

##### Expected behaviour
The app does not crash

##### OS/Hardware
- Operative System: Windows 10
- CPU: 64 bit

##### Additional context  
I have a dmp file but apparently I can't attach it here.

**Comment by WallucePinkham** [comment] 2022-12-27 22:52
[LibreSprite-crash-1.2-973d0e3d-SDL.dmp.zip](https://github.com/LibreSprite/LibreSprite/files/10311062/LibreSprite-crash-1.2-973d0e3d-SDL.dmp.zip)

**Comment by maujin111** [comment] 2022-12-29 05:57
duplicate of #343

**Closed** 2022-12-29 05:57 UTC
Labels: unconfirmed bug
