### ISSUE TITLE
Window trails while moving windows other than main window.

### ISSUE THREAD

**Issue by yuyutsupoudel** [LibreSprite/LibreSprite#72] opened 2020-07-20 13:40 UTC
A trail of window forms while moving window. It does not happens in main window but only on secondary window. like while moving "New File" and "Open File" 
[picture](https://user-images.githubusercontent.com/49397015/87944029-92942200-cabe-11ea-901c-9181c8245448.png)

**Comment by yuyutsupoudel** [comment] 2020-07-20 13:40
Happens in both linux and windows.

**Comment by PerryHugh** [comment] 2020-07-24 01:27
Confirmed.

**Comment by yuyutsupoudel** [comment] 2020-08-06 10:12
[Video](https://streamable.com/qu0dgq)

**Comment by Zughy** [comment] 2021-09-06 23:33
I guess this is related to Allegro 4? Possibly the SDL2 switch should fix it

**Comment by Zughy** [comment] 2021-09-15 23:36
Duplicate of #87, which sounds more complete. Closing

**Closed by Zughy** 2021-09-15 23:36 UTC
Labels: bug
