### ISSUE TITLE
gen.exe Flagged as a threat by Bitdefender

### ISSUE THREAD

**Issue by YouGottaBeJoshingMe** [LibreSprite/LibreSprite#83] opened 2020-11-13 19:10 UTC
Recently installed the Windows 10 port of LibreSprite, the installation went without a hitch but BitDefender somehow read gen.exe as a threat.

**Comment by maujin111** [comment] 2020-11-13 19:14
Duplicate of #64

**Closed** 2021-09-06 23:39 UTC
