### ISSUE TITLE
First click on any menu entry doesn't work

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite#314] opened 2021-11-23 19:06 UTC
##### LibreSprite version
```
6d3391 (UI refactor)
```

##### To Reproduce
Open any LibreSprite version after #283 (I've bisected it) and try to click on an entry like Edit->Preferences or Help->About. It won't work, even by clicking multiple times. To make it work you need to move the mouse outside of that specific entry and click again. It also works by clicking on the entry and, *without releasing the mouse*, moving the mouse outside of that entry, moving it back in, and then releasing

##### OS/Hardware
- Operative System: Pop!_OS 21.04
- CPU: i7 7700

**Comment by quasart** [comment] 2022-05-20 18:51
Hello everybody here !

I met the same bug, and I tried to search for the cause. 

Here:
https://github.com/LibreSprite/LibreSprite/blob/c2f2ab31a0ee81cc0300f697874724ffa0b86e4e/src/ui/menu.cpp#L461

we don't reach `executeClick` because `!highlight->m_submenu_timer` is false

removing this condition from if statement solved the problem for me, but I may have broken something related with submenus

**Comment by maujin111** [comment] 2022-05-22 09:34
i will check that

**Comment by felipemanga** [comment] 2023-12-23 14:10
Fixed by removing the commit

**Closed by felipemanga** 2023-12-23 14:10 UTC
Labels: bug, UI/UX
