### ISSUE TITLE
App crashes when selecting font in text menu

### ISSUE THREAD

**Issue by Linux-Gamer** [LibreSprite/LibreSprite#351] opened 2022-02-11 20:35 UTC
Libresprite crashes when selecting the font in text menu.

### Steps To Reproduce
- Open Libresprite.
- "T"
- select font
- then crash

###### OS
Windows 11
###### LibreSprite Version
V 1.0

**Comment by maujin111** [comment] 2022-04-24 07:15
i tried to replicate the bug and had not success, i'm on windows 10

**Comment by maujin111** [comment] 2022-05-02 08:18
Duplicate of #345

**Closed by maujin111** 2022-05-02 08:18 UTC
Labels: unconfirmed bug
