### ISSUE TITLE
Crash - Might have been my system not the app but it wanted me to report.

### ISSUE THREAD

**Issue by Linux-Gamer** [LibreSprite/LibreSprite#345] opened 2022-01-22 17:24 UTC
I was trying to use the text tool to make an asset for a game, and it crashed. Again, might have been my system, but the app wanted me to report.

**Comment by Linux-Gamer** [comment] 2022-02-01 16:17
I just tried it again on a different install of libresprite (same version) and it has done it again, when choosing font in the text popup,  the whole app crashes

**Comment by Linux-Gamer** [comment] 2022-02-01 17:06
it's on windows

**Comment by maujin111** [comment] 2022-02-01 18:00
Let me see if i got the same error

**Comment by maujin111** [comment] 2022-05-02 08:19
Duplicate of #343

**Closed by maujin111** 2022-05-02 08:19 UTC
Labels: unconfirmed bug, waiting for info
